
//ADD REPORT DESCRIPTION
export const ADD_REPORT_BUG_DESCRIPTION_REQUEST = "ADD_REPORT_BUG_DESCRIPTION_REQUEST";
export const ADD_REPORT_BUG_DESCRIPTION_SUCCESS = "ADD_REPORT_BUG_DESCRIPTION_SUCCESS";
export const ADD_REPORT_BUG_DESCRIPTION_FAILURE = "ADD_REPORT_BUG_DESCRIPTION_FAILURE";